# call in the libraries

In [22]:
import numpy as np
import pandas as pd
import seaborn as sns

In [23]:
!pip install geopandas
!pip install geopy

Collecting geopandas
  Downloading geopandas-0.13.2-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 9.1 MB/s eta 0:00:00:00:010:01
Collecting fiona>=1.8.19 (from geopandas)
  Downloading Fiona-1.9.4.post1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (16.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.4/16.4 MB 35.7 MB/s eta 0:00:0000:0100:01
Requirement already satisfied: packaging in /home/jmerrett/.pyenv/versions/3.10.6/envs/food-pandora/lib/python3.10/site-packages (from geopandas) (23.1)
Requirement already satisfied: pandas>=1.1.0 in /home/jmerrett/.pyenv/versions/3.10.6/envs/food-pandora/lib/python3.10/site-packages (from geopandas) (2.0.2)
Collecting pyproj>=3.0.1 (from geopandas)
  Downloading pyproj-3.6.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (7.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 7.9/7.9 MB 43.5 MB/s eta 0:00:0000:0100:01
Collecting shapely>=1.7.1 (from geopandas)
  Downloading shapely-2.0.1-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (2.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.3/2.3 MB 41.9 MB/s eta 0:00:0000:01
Requirement already satisfied: attrs>=19.2.0 in /home/jmerrett/.pyenv/versions/3.10.6/envs/food-pandora/lib/python3.10/site-packages (from fiona>=1.8.19->geopandas) (23.1.0)
Requirement already satisfied: certifi in /home/jmerrett/.pyenv/versions/3.10.6/envs/food-pandora/lib/python3.10/site-packages (from fiona>=1.8.19->geopandas) (2023.5.7)
Collecting click~=8.0 (from fiona>=1.8.19->geopandas)
  Using cached click-8.1.3-py3-none-any.whl (96 kB)
Collecting click-plugins>=1.0 (from fiona>=1.8.19->geopandas)
  Downloading click_plugins-1.1.1-py2.py3-none-any.whl (7.5 kB)
Collecting cligj>=0.5 (from fiona>=1.8.19->geopandas)
  Downloading cligj-0.7.2-py3-none-any.whl (7.1 kB)
Requirement already satisfied: six in /home/jmerrett/.pyenv/versions/3.10.6/envs/food-pandora/lib/python3.10/site-packages (from fiona>=1.8.19->geopandas) (1.16.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/jmerrett/.pyenv/versions/3.10.6/envs/food-pandora/lib/python3.10/site-packages (from pandas>=1.1.0->geopandas) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /home/jmerrett/.pyenv/versions/3.10.6/envs/food-pandora/lib/python3.10/site-packages (from pandas>=1.1.0->geopandas) (2023.3)
Requirement already satisfied: tzdata>=2022.1 in /home/jmerrett/.pyenv/versions/3.10.6/envs/food-pandora/lib/python3.10/site-packages (from pandas>=1.1.0->geopandas) (2023.3)
Requirement already satisfied: numpy>=1.21.0 in /home/jmerrett/.pyenv/versions/3.10.6/envs/food-pandora/lib/python3.10/site-packages (from pandas>=1.1.0->geopandas) (1.24.3)
Installing collected packages: shapely, pyproj, click, cligj, click-plugins, fiona, geopandas
Successfully installed click-8.1.3 click-plugins-1.1.1 cligj-0.7.2 fiona-1.9.4.post1 geopandas-0.13.2 pyproj-3.6.0 shapely-2.0.1
Collecting geopy
  Downloading geopy-2.3.0-py3-none-any.whl (119 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 119.8/119.8 kB 3.0 MB/s eta 0:00:00a 0:00:01
Collecting geographiclib<3,>=1.52 (from geopy)
  Downloading geographiclib-2.0-py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.3/40.3 kB 3.2 MB/s eta 0:00:00
Installing collected packages: geographiclib, geopy
Successfully installed geographiclib-2.0 geopy-2.3.0

# Import the DataSet

In [54]:
data = pd.read_csv('../raw_data/Tokyo_Restaurant_Reviews_Tabelog.csv')
df = pd.read_csv('../raw_data/restaurants_tokyo.csv')
data.head(1)

,store_id,name,nearest_station,nearest_distance,genre,rating_val,review_cnt,save_cnt,budget_dinner,budget_lunch,holiday,address,prefecture,municipalities_1,municipalities_2,municipalities_3
0,13097553,個室北国炉端 ときしらず 飯田橋駅前,飯田橋駅,82.0,魚介料理・海鮮料理、居酒屋、日本料理,3.12,61.0,2848.0,"￥3,000～￥3,999","￥3,000～￥3,999",-,東京都千代田区飯田橋4-9-8 大和ビル 5F,東京,千代田区,飯田橋,-

In [6]:
df.head()

,Unnamed: 0,Restaurant name,Categories,TEL/reservation,Addresses,Transportation,Operating Hours,Shop holidays,Budget,Method of payment,Table money/charge,Awards
0,0,Yakitonasachan(やきとん あさちゃん 戸越銀座店),"Izakaya (Tavern), Grilled pork, Yakitori (Gril...",050-5570-4876 (+81-50-5570-4876) (For ...,1-chome-8-1 Hiratsuka Shinagawa City Tokyo-to ...,東急池上線 戸越銀座駅 徒歩10秒47 meters from Togoshi Ginza.,月～木曜日 15時～23時(ラストオーダー 22:30)金曜日 15時～23時30分(ラ...,12/31 1/1 休業,"Dinner:￥2,000～￥2,999Lunch:￥2,000～￥2,999",Credit Cards AcceptedElectronic money Not Acce...,お通し(席料込み) 220円,NaN
1,1,sakabafutamata(酒場フタマタ 西新橋店),"Izakaya (Tavern), Dumplings, Yakitori (Grilled...",050-5456-6727 (+81-50-5456-6727) (For ...,1-chome-3-1 Nishishinbashi Minato City Tokyo-t...,JR新橋駅徒歩5分銀座線虎ノ門駅徒歩5分都営三田線内幸町駅A4ｂ出口直結155 meters...,[月～金]11:30～14:3017:00～23:00,土日祝 12/29~1/3 休業,"Dinner:￥2,000～￥2,999Lunch:～￥999",Credit Cards Accepted (VISA、M...,お通し：429円※コース利用の場合はなし,NaN
2,2,Maggiore(マッジョーレ),"Dining bar, Italian, Pasta",03-5610-5151 (+81-3-5610-5151) 予約可※ご予約...,Taihei Sumida City Tokyo ...,ＪＲ総武線錦糸町駅北口から徒歩７分東京メトロ半蔵門線錦糸町駅４番出口から徒歩３分401 me...,【ランチ） 11：30～14：00（L.O)平日 ランチ専用メニュー土、日、祝 アラカルトメ...,月曜日,"Dinner:￥4,000～￥4,999Lunch:￥1,000～￥1,999",Credit Cards Accepted (VISA、M...,NaN,NaN
3,3,Tanyashe(譚鴨血老火鍋 池袋東口店),"Chinese hot pot / fire pot, Izakaya (Tavern), ...",050-5872-8185 (+81-50-5872-8185) (For ...,1-chome-26-2 Minamiikebukuro Toshima City Toky...,池袋駅東口徒歩2分JR池袋駅東口を出て、目の前の大通りの左側の道をまっすぐ、マクドナルド・g...,全日11:00～23:00(Lo:22:30)Open on sundays,年中無休,"Dinner:￥3,000～￥3,999Lunch:￥1,000～￥1,999",Credit Cards Accepted (VISA、M...,チャージなし,NaN
4,4,Yakinikuinami(焼肉一七三 向山),"Yakiniku (BBQ Beef), Horumon (BBQ Offel), Izak...",050-5890-0396 (+81-50-5890-0396) (For ...,1-chome-13-3 Ebisuminami Shibuya City Tokyo ...,JR山手線ほか 恵比寿駅 西口 徒歩3分151 meters from Ebisu.,[火～日]17:00～24:00(L.O)Open on sundays,月曜日,"Dinner:￥8,000～￥9,999",Credit Cards Accepted (VISA、M...,NaN,NaN

# Explore the Data

In [10]:
df.describe()

        Unnamed: 0
count  1000.000000
mean    499.500000
std     288.819436
min       0.000000
25%     249.750000
50%     499.500000
75%     749.250000
max     999.000000

In [11]:
df.head()

,Unnamed: 0,Restaurant name,Categories,TEL/reservation,Addresses,Transportation,Operating Hours,Shop holidays,Budget,Method of payment,Table money/charge,Awards
0,0,Yakitonasachan(やきとん あさちゃん 戸越銀座店),"Izakaya (Tavern), Grilled pork, Yakitori (Gril...",050-5570-4876 (+81-50-5570-4876) (For ...,1-chome-8-1 Hiratsuka Shinagawa City Tokyo-to ...,東急池上線 戸越銀座駅 徒歩10秒47 meters from Togoshi Ginza.,月～木曜日 15時～23時(ラストオーダー 22:30)金曜日 15時～23時30分(ラ...,12/31 1/1 休業,"Dinner:￥2,000～￥2,999Lunch:￥2,000～￥2,999",Credit Cards AcceptedElectronic money Not Acce...,お通し(席料込み) 220円,NaN
1,1,sakabafutamata(酒場フタマタ 西新橋店),"Izakaya (Tavern), Dumplings, Yakitori (Grilled...",050-5456-6727 (+81-50-5456-6727) (For ...,1-chome-3-1 Nishishinbashi Minato City Tokyo-t...,JR新橋駅徒歩5分銀座線虎ノ門駅徒歩5分都営三田線内幸町駅A4ｂ出口直結155 meters...,[月～金]11:30～14:3017:00～23:00,土日祝 12/29~1/3 休業,"Dinner:￥2,000～￥2,999Lunch:～￥999",Credit Cards Accepted (VISA、M...,お通し：429円※コース利用の場合はなし,NaN
2,2,Maggiore(マッジョーレ),"Dining bar, Italian, Pasta",03-5610-5151 (+81-3-5610-5151) 予約可※ご予約...,Taihei Sumida City Tokyo ...,ＪＲ総武線錦糸町駅北口から徒歩７分東京メトロ半蔵門線錦糸町駅４番出口から徒歩３分401 me...,【ランチ） 11：30～14：00（L.O)平日 ランチ専用メニュー土、日、祝 アラカルトメ...,月曜日,"Dinner:￥4,000～￥4,999Lunch:￥1,000～￥1,999",Credit Cards Accepted (VISA、M...,NaN,NaN
3,3,Tanyashe(譚鴨血老火鍋 池袋東口店),"Chinese hot pot / fire pot, Izakaya (Tavern), ...",050-5872-8185 (+81-50-5872-8185) (For ...,1-chome-26-2 Minamiikebukuro Toshima City Toky...,池袋駅東口徒歩2分JR池袋駅東口を出て、目の前の大通りの左側の道をまっすぐ、マクドナルド・g...,全日11:00～23:00(Lo:22:30)Open on sundays,年中無休,"Dinner:￥3,000～￥3,999Lunch:￥1,000～￥1,999",Credit Cards Accepted (VISA、M...,チャージなし,NaN
4,4,Yakinikuinami(焼肉一七三 向山),"Yakiniku (BBQ Beef), Horumon (BBQ Offel), Izak...",050-5890-0396 (+81-50-5890-0396) (For ...,1-chome-13-3 Ebisuminami Shibuya City Tokyo ...,JR山手線ほか 恵比寿駅 西口 徒歩3分151 meters from Ebisu.,[火～日]17:00～24:00(L.O)Open on sundays,月曜日,"Dinner:￥8,000～￥9,999",Credit Cards Accepted (VISA、M...,NaN,NaN

In [9]:
df.tail()

,Unnamed: 0,Restaurant name,Categories,TEL/reservation,Addresses,Transportation,Operating Hours,Shop holidays,Budget,Method of payment,Table money/charge,Awards
995,995,TAMURO(酒肴場 屯),"Seafood, Izakaya (Tavern), Nihonshu (Japanese ...",050-5594-4178 (+81-50-5594-4178) (For ...,2-chome-8-17 Shinbashi Minato City Tokyo-to ...,JR新橋駅 日比谷口 徒歩2分地下鉄銀座線 新橋駅 8番出口 徒歩2分都営三田線 内幸町駅 ...,昼【月〜金】11:30〜14:30※スープがなくなり次第終了となります。夜【月〜金】17:0...,日曜、祝日,"Dinner:￥6,000～￥7,999",Credit Cards Accepted (VISA、M...,お通し(2種)代800円（税込）、サービス料5%,NaN
996,996,kanzenkoshitsukaisenshungyohananomai(完全個室・海鮮旬魚...,"Izakaya (Tavern), Seafood, Yakitori (Grilled c...",050-5592-7469 (+81-50-5592-7469) (For ...,1-chome-2-7 Kajicho Chiyoda City Tokyo-to ...,ＪＲ神田南口／西口：徒歩１分 銀座線神田駅：徒歩３分東京駅 方面より【ガード 高架下】 23...,【ディナー】月～土 17:00～23:30,日曜日、祝日,"Dinner:￥2,000～￥2,999Lunch:～￥999",Credit Cards Accepted (VISA、M...,当店は、【先付 （お通し）】として、300円 を頂いております。心ばかりのものですが、お料理...,NaN
997,997,shintoukyouyakinikuyuushinutage(新東京焼肉 遊心 宴 日本橋...,"Yakiniku (BBQ Beef), Horumon (BBQ Offel)",050-5457-0559 (+81-50-5457-0559) (For ...,1-chome-32-2 Nihonbashikakigaracho Chuo City T...,東京メトロ半蔵門線 水天宮前駅 6番出口 徒歩3分東京メトロ日比谷線 人形町駅 A2番出口 ...,ランチ全日11:30～14:00（LO13:30）ディナー月〜土17:00～23:00（フー...,不定休,"Dinner:￥5,000～￥5,999Lunch:￥1,000～￥1,999",Credit Cards Accepted (JCB、AM...,NaN,NaN
998,998,Wine no Ruisuke(Wine no Ruisuke 渋谷ストリーム店),"Bar, Fowl, Dining bar",050-5596-1074 (+81-50-5596-1074) (For ...,3-chome-21-3 Shibuya Shibuya City Tokyo-to ...,以下、沿線「渋谷駅」C2出口直結・東急東横線、田園都市線・東京メトロ半蔵門線、副都心線※JR...,★営業時間★【ランチ】平日 12：00～15：00土日祝 12：00～14：00【ディナー...,無休(ストリームに準ずる),"Dinner:￥3,000～￥3,999Lunch:￥1,000～￥1,999",Credit Cards Accepted (VISA、M...,お通し代として￥300いただいております。当店の表示価格は全て税込み価格です。別途10％のサ...,NaN
999,999,taishuuizakayayoyogiyokochou(大衆居酒屋代々木横丁),"Izakaya (Tavern), Japanese food (other), Creat...",050-5593-3787 (+81-50-5593-3787) (For ...,1-chome-31-17 Yoyogi Shibuya City Tokyo-to ...,大江戸線「代々木駅」徒歩1分JR「代々木駅」徒歩1分216 meters from Yoyogi.,【月～金】11:30～14:00(L.O.13:30)17:00～23:30(L.O.23:...,日曜は休業致します。 但し、祝日後で臨時休業する場合がございます。例：日（祝）月（振替休日）月休み,"Dinner:￥2,000～￥2,999Lunch:～￥999",Credit Cards Accepted (VISA、M...,お通し：325円（350円税込）※コースの際は無,NaN

In [12]:

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Unnamed: 0          1000 non-null   int64
 1   Restaurant name     1000 non-null   object
 2   Categories          1000 non-null   object
 3   TEL/reservation     1000 non-null   object
 4   Addresses           1000 non-null   object
 5   Transportation      1000 non-null   object
 6   Operating Hours     1000 non-null   object
 7   Shop holidays       1000 non-null   object
 8   Budget              1000 non-null   object
 9   Method of payment   1000 non-null   object
 10  Table money/charge  636 non-null    object
 11  Awards              3 non-null      object
dtypes: int64(1), object(11)
memory usage: 93.9+ KB

In [13]:
#since we will be focusing on tokyo, we can get rid of the prefecture collumn
#not sure how useful municipalities_3 will be maybe get rid of it. 
df.nunique()

Unnamed: 0            1000
Restaurant name        980
Categories             689
TEL/reservation        980
Addresses              975
Transportation         980
Operating Hours        972
Shop holidays          443
Budget                  66
Method of payment      251
Table money/charge     457
Awards                   3
dtype: int64

In [14]:
# looks like nearest_station, Rating_value, rating_cnt, save_cnt, have missing df.
(df.isnull().sum())/df.count()

Unnamed: 0              0.000000
Restaurant name         0.000000
Categories              0.000000
TEL/reservation         0.000000
Addresses               0.000000
Transportation          0.000000
Operating Hours         0.000000
Shop holidays           0.000000
Budget                  0.000000
Method of payment       0.000000
Table money/charge      0.572327
Awards                332.333333
dtype: float64

## Quickly drop duplicates

In [16]:
df.drop_duplicates()

,Unnamed: 0,Restaurant name,Categories,TEL/reservation,Addresses,Transportation,Operating Hours,Shop holidays,Budget,Method of payment,Table money/charge,Awards
0,0,Yakitonasachan(やきとん あさちゃん 戸越銀座店),"Izakaya (Tavern), Grilled pork, Yakitori (Gril...",050-5570-4876 (+81-50-5570-4876) (For ...,1-chome-8-1 Hiratsuka Shinagawa City Tokyo-to ...,東急池上線 戸越銀座駅 徒歩10秒47 meters from Togoshi Ginza.,月～木曜日 15時～23時(ラストオーダー 22:30)金曜日 15時～23時30分(ラ...,12/31 1/1 休業,"Dinner:￥2,000～￥2,999Lunch:￥2,000～￥2,999",Credit Cards AcceptedElectronic money Not Acce...,お通し(席料込み) 220円,NaN
1,1,sakabafutamata(酒場フタマタ 西新橋店),"Izakaya (Tavern), Dumplings, Yakitori (Grilled...",050-5456-6727 (+81-50-5456-6727) (For ...,1-chome-3-1 Nishishinbashi Minato City Tokyo-t...,JR新橋駅徒歩5分銀座線虎ノ門駅徒歩5分都営三田線内幸町駅A4ｂ出口直結155 meters...,[月～金]11:30～14:3017:00～23:00,土日祝 12/29~1/3 休業,"Dinner:￥2,000～￥2,999Lunch:～￥999",Credit Cards Accepted (VISA、M...,お通し：429円※コース利用の場合はなし,NaN
2,2,Maggiore(マッジョーレ),"Dining bar, Italian, Pasta",03-5610-5151 (+81-3-5610-5151) 予約可※ご予約...,Taihei Sumida City Tokyo ...,ＪＲ総武線錦糸町駅北口から徒歩７分東京メトロ半蔵門線錦糸町駅４番出口から徒歩３分401 me...,【ランチ） 11：30～14：00（L.O)平日 ランチ専用メニュー土、日、祝 アラカルトメ...,月曜日,"Dinner:￥4,000～￥4,999Lunch:￥1,000～￥1,999",Credit Cards Accepted (VISA、M...,NaN,NaN
3,3,Tanyashe(譚鴨血老火鍋 池袋東口店),"Chinese hot pot / fire pot, Izakaya (Tavern), ...",050-5872-8185 (+81-50-5872-8185) (For ...,1-chome-26-2 Minamiikebukuro Toshima City Toky...,池袋駅東口徒歩2分JR池袋駅東口を出て、目の前の大通りの左側の道をまっすぐ、マクドナルド・g...,全日11:00～23:00(Lo:22:30)Open on sundays,年中無休,"Dinner:￥3,000～￥3,999Lunch:￥1,000～￥1,999",Credit Cards Accepted (VISA、M...,チャージなし,NaN
4,4,Yakinikuinami(焼肉一七三 向山),"Yakiniku (BBQ Beef), Horumon (BBQ Offel), Izak...",050-5890-0396 (+81-50-5890-0396) (For ...,1-chome-13-3 Ebisuminami Shibuya City Tokyo ...,JR山手線ほか 恵比寿駅 西口 徒歩3分151 meters from Ebisu.,[火～日]17:00～24:00(L.O)Open on sundays,月曜日,"Dinner:￥8,000～￥9,999",Credit Cards Accepted (VISA、M...,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
995,995,TAMURO(酒肴場 屯),"Seafood, Izakaya (Tavern), Nihonshu (Japanese ...",050-5594-4178 (+81-50-5594-4178) (For ...,2-chome-8-17 Shinbashi Minato City Tokyo-to ...,JR新橋駅 日比谷口 徒歩2分地下鉄銀座線 新橋駅 8番出口 徒歩2分都営三田線 内幸町駅 ...,昼【月〜金】11:30〜14:30※スープがなくなり次第終了となります。夜【月〜金】17:0...,日曜、祝日,"Dinner:￥6,000～￥7,999",Credit Cards Accepted (VISA、M...,お通し(2種)代800円（税込）、サービス料5%,NaN
996,996,kanzenkoshitsukaisenshungyohananomai(完全個室・海鮮旬魚...,"Izakaya (Tavern), Seafood, Yakitori (Grilled c...",050-5592-7469 (+81-50-5592-7469) (For ...,1-chome-2-7 Kajicho Chiyoda City Tokyo-to ...,ＪＲ神田南口／西口：徒歩１分 銀座線神田駅：徒歩３分東京駅 方面より【ガード 高架下】 23...,【ディナー】月～土 17:00～23:30,日曜日、祝日,"Dinner:￥2,000～￥2,999Lunch:～￥999",Credit Cards Accepted (VISA、M...,当店は、【先付 （お通し）】として、300円 を頂いております。心ばかりのものですが、お料理...,NaN
997,997,shintoukyouyakinikuyuushinutage(新東京焼肉 遊心 宴 日本橋...,"Yakiniku (BBQ Beef), Horumon (BBQ Offel)",050-5457-0559 (+81-50-5457-0559) (For ...,1-chome-32-2 Nihonbashikakigaracho Chuo City T...,東京メトロ半蔵門線 水天宮前駅 6番出口 徒歩3分東京メトロ日比谷線 人形町駅 A2番出口 ...,ランチ全日11:30～14:00（LO13:30）ディナー月〜土17:00～23:00（フー...,不定休,"Dinner:￥5,000～￥5,999Lunch:￥1,000～￥1,999",Credit Cards Accepted (JCB、AM...,NaN,NaN
998,998,Wine no Ruisuke(Wine no Ruisuke 渋谷ストリーム店),"Bar, Fowl, Dining bar",050-5596-1074 (+81-50-5596-1074) (For ...,3-chome-21-3 Shibuya Shibuya City Tokyo-to ...,以下、沿線「渋谷駅」C2出口直結・東急東横線、田園都市線・東京メトロ半蔵門線、副都心線※JR...,★営業時間★【ランチ】平日 12：00～15：00土日祝 12：00～14：00【ディナー...,無休(ストリームに準ずる),"Dinner:￥3,000～￥3,999Lunch:￥1,000～￥1,999",Credit Cards Accepted (VISA、M...,お通し代として￥300いただいております。当店の表示価格は全て税込み価格です。別途10％のサ...,NaN
999,999,taishuuizakayayoyogiyokochou(大衆居酒屋代々木横丁),"Izakaya (Tavern), Japanese food (other), Creat...",050-5593-3787 (+81-50-5593-3787) (For ...,1-chome-31-17 Yoyogi Shibuya City Tokyo-to ...,大江戸線「代々木駅」徒歩1分JR「代々木駅」徒歩1分216 meters from Yoyogi.,【月～金】11:30～14:00(L.O.13:30)17:00～23:30(L.O.23:...,日曜は休業致します。 但し、祝日後で臨時休業する場合がございます。例：日（祝）月（振替休日）月休み,"Dinner:￥2,000～￥2,999Lunch:～￥999",Credit Cards Accepted (VISA、M...,お通し：325円（350円税込）※コースの際は無,NaN

## Drop Unecessary Columns

In [20]:
# From the missing data above we need to drop the Awards and Table Money/Charge. they are unimportant and missing too much data.
df.drop('Table money/charge', inplace = True, axis = 1)
df.drop('Awards', inplace = True, axis = 1)

In [21]:
df.head(1)

,Unnamed: 0,Restaurant name,Categories,TEL/reservation,Addresses,Transportation,Operating Hours,Shop holidays,Budget,Method of payment
0,0,Yakitonasachan(やきとん あさちゃん 戸越銀座店),"Izakaya (Tavern), Grilled pork, Yakitori (Gril...",050-5570-4876 (+81-50-5570-4876) (For ...,1-chome-8-1 Hiratsuka Shinagawa City Tokyo-to ...,東急池上線 戸越銀座駅 徒歩10秒47 meters from Togoshi Ginza.,月～木曜日 15時～23時(ラストオーダー 22:30)金曜日 15時～23時30分(ラ...,12/31 1/1 休業,"Dinner:￥2,000～￥2,999Lunch:￥2,000～￥2,999",Credit Cards AcceptedElectronic money Not Acce...

# Deciding How to Encode the objects

In [ ]:
# address can be changed into lan and lon
# Method of payment can be turned into accepts credit or not
# budget can be changed into the google version of 1 being from cheap to 4 being expensive
# Resturant name, telephone, operation hours are all important, but cannot be used to train the model. 
# transportation can be changed into meters from nearest station

### Address -> Coordinates

In [58]:
from geopy.extra.rate_limiter import RateLimiter
from geopy.geocoders import Nominatim

In [59]:
df['Addresses'].head()

0    1-chome-8-1 Hiratsuka Shinagawa City Tokyo-to ...
1    1-chome-3-1 Nishishinbashi Minato City Tokyo-t...
2    Taihei Sumida City Tokyo                      ...
3    1-chome-26-2 Minamiikebukuro Toshima City Toky...
4    1-chome-13-3 Ebisuminami Shibuya City Tokyo   ...
Name: Addresses, dtype: object

In [60]:
geolocator = Nominatim(user_agent='myGeocoder')

In [61]:
# create a fuction to make it easier to have geocalls
geocode = RateLimiter(locator.geocode, min_delay_seconds=1)

In [64]:
latitudes = []
longitudes = []
altitudes = []

# Iterate over each address in the column
for address in df['Addresses']:
    # Perform geocoding
    location = geolocator.geocode(address)
    
    # If a location is found, append the latitude, longitude, and altitude to the respective lists
    if location:
        latitudes.append(location.latitude)
        longitudes.append(location.longitude)
        altitudes.append(location.altitude)
    else:
        # If no location is found, append None values
        latitudes.append(None)
        longitudes.append(None)
        altitudes.append(None)

# Add the latitude, longitude, and altitude lists as new columns in the DataFrame
# df'latitude'] = latitudes
# df['longitude'] = longitudes
# df['altitude'] = altitudes

In [65]:
latitudes

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [52]:
df'latitude'] = latitudes
df['longitude'] = longitudes
df['altitude'] = altitudes

0    None
Name: Addresses, dtype: object

0      None
1      None
2      None
3      None
4      None
       ...
995    None
996    None
997    None
998    None
999    None
Name: point, Length: 1000, dtype: object

In [48]:
# split the columns into individual columns
df[['latitude', 'longitude', 'altitude']] = pd.DataFrame(df['point'].tolist(), index=df.index)

ValueError: Columns must be same length as key

### Method of payment can be turned into accepts credit or not

### Budget to scale (1-4)

### Transportation to meters from nearest station

# KNN is the way to go

## import the libraries

In [ ]:
from sklearn.neighbors import KNeighborsRegressor
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error

## pick my X and y

In [ ]:
X = 
y =

## split into train and test data

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
k = 5  # Number of neighbors to consider (you can adjust this value)
knn = KNeighborsRegressor(n_neighbors=k)

In [ ]:
knn.fit(X_train, y_train)

In [ ]:
y_pred = knn.predict(X_test)

In [ ]:
mse = mean_squared_error(y_test, y_pred)